Shopping/Components/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping.Data;

namespace Shopping.Components
{
	public class BrandsViewComponent:ViewComponent
	{
		private readonly ShoppingDbContext _db;

		public BrandsViewComponent(ShoppingDbContext db)
		{
			_db = db;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View(await _db.Brands.Include(x=>x.Products).ToListAsync());
		}
	}
}

Shopping/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping.Data;

namespace Shopping.Controllers
{
    public class BrandController : Controller
    {
        private readonly ShoppingDbContext _db;

        public BrandController(ShoppingDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(string Slug)
        {
            if (string.IsNullOrEmpty(Slug))
            {
                return RedirectToAction("Index");
            }

            var brand = await this._db.Brands.FirstOrDefaultAsync(x => x.Slug == Slug);
            if (brand == null)
            {
                return RedirectToAction("Index");
            }

            var productsByBrand = await this._db.Products
                                                .Where(x => x.BrandId == brand.Id)
                                                .ToListAsync();

            return View(productsByBrand);
        }
    }
}

Shopping/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping.Data;
using Shopping.Models;

namespace Shopping.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ShoppingDbContext _db;

        public CategoryController(ShoppingDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(string Slug)
        {
            var category = await this._db.Categories.Where(x=>x.Slug== Slug).FirstOrDefaultAsync();    
            if (category == null)
            {
                return RedirectToAction("Index");
            }
            var productByCategory = this._db.Products.Where(x => x.CategoryId == category.Id);

            return View(await productByCategory.OrderByDescending(x=>x.Id).ToListAsync());
        }
    }
}

Shopping/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shopping.Data;

namespace Shopping.Controllers
{
    public class ProductController : Controller
    {
        private readonly ShoppingDbContext _db;

        public ProductController(ShoppingDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Detail(int Id)
        {
            var product =await this._db.Products.FirstOrDefaultAsync(x=>x.Id == Id);
            return View(product);
        }
    }
}

Shopping/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Admin | E-Shopper</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/css/price-range.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="~/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>


    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="index.html"><img src="images/home/logo.png" alt="" /></a>
                        </div>
                        <div class="btn-group pull-right">
                        </div>
                    </div>

                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a asp-controller="Product" asp-action="Index" class="active">Home</a></li>
                                <li>
                                    <a asp-action="Index" asp-controller="Category">Categories</a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Brand">Brand</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="search_box pull-right">
                            <input type="text" placeholder="Search" />
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->
    <section>
        <div class="container">
            <div class="row">
                @await Html.PartialAsync("_NotificationPartial")
                @RenderBody()
            </div>
        </div>
    </section>

    <footer id="footer">
        <!--Footer-->

    </footer><!--/Footer-->



    <script src="~/js/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/price-range.js"></script>
    <script src="~/js/jquery.prettyPhoto.js"></script>
    <script src="~/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if(TempData["success"]!=null){
    <div class="alert alert-success notification">
        @TempData["success"]
    </div>
}
@if (TempData["error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["error"]
    </div>
}

Shopping/Areas/Admin/Views/Shared/_ProductPartial.cshtml
@model Product
<div class="col-sm-4">
    <div class="product-image-wrapper">

        <div class="single-products">

            <div class="productinfo text-center">
                <a asp-action="Detail" asp-controller="Product" asp-route-Id="@Model.Id">
                    <img src="~/images/Product/@Model.Images" alt="@Model.Name" />
                    <h2>$@Model.Price</h2>
                    <p>@Model.Name</p>
                    <p>Danh Mục : @Model.Category.Name</p>
                    <p>Hãng Sản Xuất : @Model.Brand.Name</p>
                    <a asp-action="AddToCart" asp-controller="Cart" asp-route-Id="@Model.Id" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>

                </a>
                    
            </div>

        </div>

        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
            </ul>
        </div>
    </div>
</div>

Shopping/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<div class="left-sidebar">
	<h2>Category</h2>
	<div class="panel-group category-products" id="accordian">
		<!--category-productsr-->	
	 <vc:categories></vc:categories>
	</div><!--/category-products-->

	<div class="brands_products">
		<!--brands_products-->
		<h2>Brands</h2>
		<div class="brands-name">
			<vc:brands></vc:brands>
		</div>
	</div><!--/brands_products-->

	<div class="price-range">
		<!--price-range-->
		<h2>Price Range</h2>
		<div class="well text-center">
			<input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br />
			<b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
		</div>
	</div><!--/price-range-->

	<div class="shipping text-center">
		<!--shipping-->
		<img src="images/home/shipping.jpg" alt="" />
	</div><!--/shipping-->

</div>